config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :modalidades

  resources :usuarios

  resources :welcomes
  
  root "posts#index"
  
  resources :usuario_session
  match 'login', to: 'usuario_session#new', via: [:get, :post]
  match 'login/create', to: 'usuario_session#create', via: :post
  match 'login/login/create', to: 'usuario_session#create', via: :post
  match 'logout', to: 'usuario_session#destroy', via: [:get, :post]
  post "usuario_session/new"

end

app/models/modalidade.rb
class Modalidade < ActiveRecord::Base
    has_and_belongs_to_many :usuarios
end

app/controllers/modalidades_controller.rb
class ModalidadesController < ApplicationController
  before_action :set_modalidade, only: [:show, :edit, :update, :destroy]

  # GET /modalidades
  # GET /modalidades.json
  def index
    @modalidades = Modalidade.all
  end

  # GET /modalidades/1
  # GET /modalidades/1.json
  def show
  end

  # GET /modalidades/new
  def new
    @modalidade = Modalidade.new
  end

  # GET /modalidades/1/edit
  def edit
  end

  # POST /modalidades
  # POST /modalidades.json
  def create
    @modalidade = Modalidade.new(modalidade_params)

    respond_to do |format|
      if @modalidade.save
        format.html { redirect_to @modalidade, notice: 'Modalidade was successfully created.' }
        format.json { render :show, status: :created, location: @modalidade }
      else
        format.html { render :new }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modalidades/1
  # PATCH/PUT /modalidades/1.json
  def update
    respond_to do |format|
      if @modalidade.update(modalidade_params)
        format.html { redirect_to @modalidade, notice: 'Modalidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @modalidade }
      else
        format.html { render :edit }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modalidades/1
  # DELETE /modalidades/1.json
  def destroy
    @modalidade.destroy
    respond_to do |format|
      format.html { redirect_to modalidades_url, notice: 'Modalidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modalidade
      @modalidade = Modalidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modalidade_params
      params.require(:modalidade).permit(:nome, :descricao)
    end
end

app/helpers/modalidades_helper.rb
module ModalidadesHelper
end

app/views/modalidades/_form.html.erb
<%= form_for(@modalidade) do |f| %>
  <% if @modalidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@modalidade.errors.count, "error") %> prohibited this modalidade from being saved:</h2>

      <ul>
      <% @modalidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modalidades/edit.html.erb
<h1>Editing modalidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @modalidade %> |
<%= link_to 'Back', modalidades_path %>

app/views/modalidades/index.html.erb
<h1>Listing modalidades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modalidades.each do |modalidade| %>
      <tr>
        <td><%= modalidade.nome %></td>
        <td><%= modalidade.descricao %></td>
        <td><%= link_to 'Show', modalidade %></td>
        <td><%= link_to 'Edit', edit_modalidade_path(modalidade) %></td>
        <td><%= link_to 'Destroy', modalidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Modalidade', new_modalidade_path %>

app/views/modalidades/new.html.erb
<h1>New modalidade</h1>

<%= render 'form' %>

<%= link_to 'Back', modalidades_path %>

app/views/modalidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @modalidade.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @modalidade.descricao %>
</p>

<%= link_to 'Edit', edit_modalidade_path(@modalidade) %> |
<%= link_to 'Back', modalidades_path %>