config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :modalidades

  resources :usuarios

  resources :welcomes
  
  root "posts#index"
  
  resources :usuario_session
  match 'login', to: 'usuario_session#new', via: [:get, :post]
  match 'login/create', to: 'usuario_session#create', via: :post
  match 'login/login/create', to: 'usuario_session#create', via: :post
  match 'logout', to: 'usuario_session#destroy', via: [:get, :post]
  post "usuario_session/new"

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
    has_many :posts
    has_and_belongs_to_many :modalidades
    #before_save :encrypt_password
    #has_secure_password
    #attr_accessor :salt
    
    validates_presence_of :nome, :cpf,:rg, :email, :senha
    validates_uniqueness_of :email
    
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    
    def self.authenticate(email, senha)
        user = Usuario.find_by_email(email)
        if user && user.senha == senha
          user
        else
          nil
        end
    end
    
    def encrypt_password
        if senha.present?
            self.senha_salt = BCrypt::Engine.generate_salt
            self.senha_hash = BCrypt::Engine.hash_secret(senha, senha_salt)
        end
    end
    
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        #UserMailer.welcome_email(@usuario).deliver_later
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :cpf, :rg, :email, :senha, :status)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for @usuario, :html => { :class => "form-horizontal usuario" } do |f| %>

    <% if @usuario.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @usuario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%= error_span(@usuario[:nome]) %>
  </div>
  <div class="control-group">
    <%= f.label :cpf, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cpf, :class => 'form-control' %>
    </div>
    <%= error_span(@usuario[:cpf]) %>
  </div>
  <div class="control-group">
    <%= f.label :rg, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rg, :class => 'form-control' %>
    </div>
    <%= error_span(@usuario[:rg]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@usuario[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :senha, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :senha, :class => 'form-control' %>
    </div>
    <%= error_span(@usuario[:senha]) %>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%= error_span(@usuario[:status]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            usuarios_path, :class => 'btn btn-default' %>

<% end %>

app/views/usuarios/edit.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuarios/index.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:rg) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.id, usuario_path(usuario) %></td>
        <td><%= usuario.nome %></td>
        <td><%= usuario.cpf %></td>
        <td><%= usuario.rg %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.status %></td>
        <td><%=l usuario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_usuario_path(usuario), :class => 'btn btn-default btn-xs' %>
          <%= button_to "delete", usuario, :method=>:delete, :class=>'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_usuario_path,
            :class => 'btn btn-primary' %>

app/views/usuarios/new.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuarios/show.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @usuario.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cpf) %>:</strong></dt>
  <dd><%= @usuario.cpf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rg) %>:</strong></dt>
  <dd><%= @usuario.rg %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @usuario.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:senha) %>:</strong></dt>
  <dd><%= @usuario.senha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @usuario.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              usuarios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_usuario_path(@usuario), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              usuario_path(@usuario),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>